name: MkDocs

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        pip install mkdocs-material mkdocs-mermaid2-plugin
    - name: Check broken links
      uses: lycheeverse/lychee-action@v1
      with:
        args: --verbose --no-progress 05_DOCUMENTATION/mkdocs-site/docs/ README.md index.html

    - name: Lint & Build MkDocs
      run: |
        cd 05_DOCUMENTATION/mkdocs-site
        pip install mkdocs-material mkdocs-mermaid2-plugin
        mkdocs build --strict
